apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: standard
  claimRef:
    name: foo-pvc
    namespace: default
  accessModes: 
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle